### PR TITLE
Use system directory separator

### PR DESCRIPTION
**Pull request by DizhovskyyD**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | ❌

### CODE REVIEW

**Comment by vjik** [comment]
In windows correct work both separators: `\`, `/`, in linux only `/`. So we can use `/` for directory separator in this cases instead of constant `DIRECTORY_SEPARATOR`.

**Comment by samdark** [comment]
As @vjik mentioned, it currently works well in Windows. @DizhovskyyD is there something that doesn't currently work well?

**Comment by DizhovskyyD** [comment]
Sorry, there was an error in my code.
I try to help the community in the development of yii3, but I don't
always immediately figure out where my mistake is.

2021-11-26 8:50 GMT+02:00, Alexander Makarov ***@***.***>:

**Comment by samdark** [comment]
That's OK. Thanks for trying to help.

**Pull request closed without merging**
